### PR TITLE
Feature/drawer

### PR DESCRIPTION
**Pull request by kalleericson**
screen shot 2018-08-22 at 14 31 59

Drawer component, used for filters in Statistics component. Fixed position, hidden off canvas when not active.

### CODE REVIEW

**Comment by kalleericson** [comment]
Märkligt - vad har jag gjort för fel här? 
Borde väl bara läggas till som en ändring, varför blir det konflikt?..

@knegusen 

```
<<<<<<< feature/drawer
    "react-accessible-accordion": "^2.4.4",
=======
>>>>>>> master```

**Comment by knegusen** [comment]
The diff looks too big. Something wrong?

**Comment by kalleericson** [comment]
Huh? The only conflict in package.json is that one row. I don't understand what's conflicting about it?

**Comment by knegusen** [comment]
There is a lot of card related code that shouldn't be in this pr, right?

**Pull request closed without merging**
